name: 'ProjectHelper Update Between Projects'
description: 'Sync customer fields content between projects'
author: "rulasg"
branding:
  icon: "table"
  color: "purple"
inputs:
  SourceOwner:
    description: 'Source Project Owner'
    required: true
  SourceProjectNumber:
    description: 'Source Project Number'
    required: true
  DestinationOwner:
    description: 'Destination Project Owner'
    required: true
  DestinationProjectNumber:
    description: 'Destination Project Number'
    required: true
  FieldSlug:
    description: 'Field Slug'
    required: true
  TOKEN:
    description: 'GitHub Token'
    required: true
  SkipInitialDestinationSync:
    description: 'Skip initial synchronization of the destination project'
    required: false
    default: "false"
  SkipInitialSourceSync:
    description: 'Skip initial synchronization of the source project'
    required: false
    default: "false"
  SkipFinalDestinationSync:
    description: 'Skip final synchronization of the destination project'
    required: false
    default: "false"
outputs:
  updated-count:
    description: "Number of items that have been updated"
    value: ${{steps.update-run.outputs.updated-count}}
runs:
  using: "composite"
  steps:
    - name: Run ProjectHelper
      id: update-run
      env:
        GH_TOKEN: ${{ inputs.TOKEN }}
      shell: pwsh
      run: |

        #Load Module
        Import-Module -Name ProjectHelper

        # Get parameters from inputs
        $NoRefreshDestination =     "${{ inputs.SkipInitialDestinationSync }}" -eq "true"
        $NoRefreshSource =          "${{ inputs.SkipInitialSourceSync }}" -eq "true"
        $NoSyncDestination =        "${{ inputs.SkipFinalDestinationSync }}" -eq "true"

        # Project Update run
        $params = @{
          SourceOwner =              "${{ inputs.SourceOwner }}"
          SourceProjectNumber =      "${{ inputs.SourceProjectNumber }}"
          DestinationOwner =         "${{ inputs.DestinationOwner }}"
          DestinationProjectNumber = "${{ inputs.DestinationProjectNumber }}"
          FieldSlug =                "${{ inputs.FieldSlug }}"
          NoRefreshDestination =     $NoRefreshDestination
          NoRefreshSource =          $NoRefreshSource
        }
        "Calling Update-ProjectItemsBetweenProjects with parameter:" | write-host
        $params | ConvertTo-Json | Out-String | write-host

        Update-ProjectItemsBetweenProjects @params

    - name: Show Update Results
      id: show-update-results
      shell: pwsh
      run: |

        #Load Module
        Import-Module -Name ProjectHelper

        # Read staged items
        $staged = Show-ProjectItemStaged

        # Output the changes to the console
        $staged | ForEach-Object { "`nItem: $($_.id) - $($_.Title)`n"; Show-ProjectItemStaged -Id $_.id | ConvertTo-Json -Depth 5 | Out-String }

        if(-not $NoSyncDestination)
        {
          # Sync staged items to project
          "Syncing staged items to project..." | write-host
          Sync-ProjectItemStaged
        } else {
          "Skipping final sync to destination project..." | write-host
        }

        # Set output value
        $count = $staged.Count ?? 0
        "updated-count output : $count" | write-host
        echo "updated-count = $count" >> $GITHUB_OUTPUT

